/* tslint:disable */
/* eslint-disable */
/**
 * Prueba API
 * This Api will be responsible for overall data distribution
 *
 * The version of the OpenAPI document: v1
 * Contact: laihan758.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { AuthorDto } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
/**
 * AuthorsApi - axios parameter creator
 * @export
 */
export const AuthorsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsDeleteAuthorIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiAuthorsDeleteAuthorIdDelete', 'id', id)
            const localVarPath = `/api/Authors/DeleteAuthor/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsGetAuthorByIdIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiAuthorsGetAuthorByIdIdGet', 'id', id)
            const localVarPath = `/api/Authors/GetAuthorById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsGetAuthorsGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authors/GetAuthors`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {AuthorDto} [authorDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsPostAuthorPost: async (authorDto?: AuthorDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Authors/PostAuthor`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authorDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {AuthorDto} [authorDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsPutAuthorIdPut: async (id: number, authorDto?: AuthorDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiAuthorsPutAuthorIdPut', 'id', id)
            const localVarPath = `/api/Authors/PutAuthor/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(authorDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * AuthorsApi - functional programming interface
 * @export
 */
export const AuthorsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AuthorsApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthorsDeleteAuthorIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthorsDeleteAuthorIdDelete(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthorsApi.apiAuthorsDeleteAuthorIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthorsGetAuthorByIdIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthorsGetAuthorByIdIdGet(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthorsApi.apiAuthorsGetAuthorByIdIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthorsGetAuthorsGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AuthorDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthorsGetAuthorsGet(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthorsApi.apiAuthorsGetAuthorsGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {AuthorDto} [authorDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthorsPostAuthorPost(authorDto?: AuthorDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthorsPostAuthorPost(authorDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthorsApi.apiAuthorsPostAuthorPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {AuthorDto} [authorDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiAuthorsPutAuthorIdPut(id: number, authorDto?: AuthorDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiAuthorsPutAuthorIdPut(id, authorDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['AuthorsApi.apiAuthorsPutAuthorIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * AuthorsApi - factory interface
 * @export
 */
export const AuthorsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AuthorsApiFp(configuration)
    return {
        /**
         * 
         * @param {AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsDeleteAuthorIdDelete(requestParameters: AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthorsDeleteAuthorIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsGetAuthorByIdIdGet(requestParameters: AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthorsGetAuthorByIdIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsGetAuthorsGet(options?: AxiosRequestConfig): AxiosPromise<Array<AuthorDto>> {
            return localVarFp.apiAuthorsGetAuthorsGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthorsApiApiAuthorsPostAuthorPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsPostAuthorPost(requestParameters: AuthorsApiApiAuthorsPostAuthorPostRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthorsPostAuthorPost(requestParameters.authorDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {AuthorsApiApiAuthorsPutAuthorIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiAuthorsPutAuthorIdPut(requestParameters: AuthorsApiApiAuthorsPutAuthorIdPutRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiAuthorsPutAuthorIdPut(requestParameters.id, requestParameters.authorDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiAuthorsDeleteAuthorIdDelete operation in AuthorsApi.
 * @export
 * @interface AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest
 */
export interface AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthorsApiApiAuthorsDeleteAuthorIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for apiAuthorsGetAuthorByIdIdGet operation in AuthorsApi.
 * @export
 * @interface AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest
 */
export interface AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthorsApiApiAuthorsGetAuthorByIdIdGet
     */
    readonly id: number
}

/**
 * Request parameters for apiAuthorsPostAuthorPost operation in AuthorsApi.
 * @export
 * @interface AuthorsApiApiAuthorsPostAuthorPostRequest
 */
export interface AuthorsApiApiAuthorsPostAuthorPostRequest {
    /**
     * 
     * @type {AuthorDto}
     * @memberof AuthorsApiApiAuthorsPostAuthorPost
     */
    readonly authorDto?: AuthorDto
}

/**
 * Request parameters for apiAuthorsPutAuthorIdPut operation in AuthorsApi.
 * @export
 * @interface AuthorsApiApiAuthorsPutAuthorIdPutRequest
 */
export interface AuthorsApiApiAuthorsPutAuthorIdPutRequest {
    /**
     * 
     * @type {number}
     * @memberof AuthorsApiApiAuthorsPutAuthorIdPut
     */
    readonly id: number

    /**
     * 
     * @type {AuthorDto}
     * @memberof AuthorsApiApiAuthorsPutAuthorIdPut
     */
    readonly authorDto?: AuthorDto
}

/**
 * AuthorsApi - object-oriented interface
 * @export
 * @class AuthorsApi
 * @extends {BaseAPI}
 */
export class AuthorsApi extends BaseAPI {
    /**
     * 
     * @param {AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public apiAuthorsDeleteAuthorIdDelete(requestParameters: AuthorsApiApiAuthorsDeleteAuthorIdDeleteRequest, options?: AxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).apiAuthorsDeleteAuthorIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public apiAuthorsGetAuthorByIdIdGet(requestParameters: AuthorsApiApiAuthorsGetAuthorByIdIdGetRequest, options?: AxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).apiAuthorsGetAuthorByIdIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public apiAuthorsGetAuthorsGet(options?: AxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).apiAuthorsGetAuthorsGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthorsApiApiAuthorsPostAuthorPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public apiAuthorsPostAuthorPost(requestParameters: AuthorsApiApiAuthorsPostAuthorPostRequest = {}, options?: AxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).apiAuthorsPostAuthorPost(requestParameters.authorDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {AuthorsApiApiAuthorsPutAuthorIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AuthorsApi
     */
    public apiAuthorsPutAuthorIdPut(requestParameters: AuthorsApiApiAuthorsPutAuthorIdPutRequest, options?: AxiosRequestConfig) {
        return AuthorsApiFp(this.configuration).apiAuthorsPutAuthorIdPut(requestParameters.id, requestParameters.authorDto, options).then((request) => request(this.axios, this.basePath));
    }
}

