/* tslint:disable */
/* eslint-disable */
/**
 * Prueba API
 * This Api will be responsible for overall data distribution
 *
 * The version of the OpenAPI document: v1
 * Contact: laihan758.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import { BookDto } from '../models';
// @ts-ignore
import { ProblemDetails } from '../models';
/**
 * BooksApi - axios parameter creator
 * @export
 */
export const BooksApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksDeleteBookIdDelete: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiBooksDeleteBookIdDelete', 'id', id)
            const localVarPath = `/api/Books/DeleteBook/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksGetBookByIdIdGet: async (id: number, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiBooksGetBookByIdIdGet', 'id', id)
            const localVarPath = `/api/Books/GetBookById/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksGetBooksGet: async (options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Books/GetBooks`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {BookDto} [bookDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksPostBookPost: async (bookDto?: BookDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/Books/PostBook`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bookDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {number} id 
         * @param {BookDto} [bookDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksPutBookIdPut: async (id: number, bookDto?: BookDto, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('apiBooksPutBookIdPut', 'id', id)
            const localVarPath = `/api/Books/PutBook/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(bookDto, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * BooksApi - functional programming interface
 * @export
 */
export const BooksApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = BooksApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBooksDeleteBookIdDelete(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBooksDeleteBookIdDelete(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BooksApi.apiBooksDeleteBookIdDelete']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBooksGetBookByIdIdGet(id: number, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBooksGetBookByIdIdGet(id, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BooksApi.apiBooksGetBookByIdIdGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBooksGetBooksGet(options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<BookDto>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBooksGetBooksGet(options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BooksApi.apiBooksGetBooksGet']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {BookDto} [bookDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBooksPostBookPost(bookDto?: BookDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBooksPostBookPost(bookDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BooksApi.apiBooksPostBookPost']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
        /**
         * 
         * @param {number} id 
         * @param {BookDto} [bookDto] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async apiBooksPutBookIdPut(id: number, bookDto?: BookDto, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.apiBooksPutBookIdPut(id, bookDto, options);
            const index = configuration?.serverIndex ?? 0;
            const operationBasePath = operationServerMap['BooksApi.apiBooksPutBookIdPut']?.[index]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, operationBasePath || basePath);
        },
    }
};

/**
 * BooksApi - factory interface
 * @export
 */
export const BooksApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = BooksApiFp(configuration)
    return {
        /**
         * 
         * @param {BooksApiApiBooksDeleteBookIdDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksDeleteBookIdDelete(requestParameters: BooksApiApiBooksDeleteBookIdDeleteRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiBooksDeleteBookIdDelete(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BooksApiApiBooksGetBookByIdIdGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksGetBookByIdIdGet(requestParameters: BooksApiApiBooksGetBookByIdIdGetRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiBooksGetBookByIdIdGet(requestParameters.id, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksGetBooksGet(options?: AxiosRequestConfig): AxiosPromise<Array<BookDto>> {
            return localVarFp.apiBooksGetBooksGet(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BooksApiApiBooksPostBookPostRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksPostBookPost(requestParameters: BooksApiApiBooksPostBookPostRequest = {}, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiBooksPostBookPost(requestParameters.bookDto, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {BooksApiApiBooksPutBookIdPutRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        apiBooksPutBookIdPut(requestParameters: BooksApiApiBooksPutBookIdPutRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.apiBooksPutBookIdPut(requestParameters.id, requestParameters.bookDto, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for apiBooksDeleteBookIdDelete operation in BooksApi.
 * @export
 * @interface BooksApiApiBooksDeleteBookIdDeleteRequest
 */
export interface BooksApiApiBooksDeleteBookIdDeleteRequest {
    /**
     * 
     * @type {number}
     * @memberof BooksApiApiBooksDeleteBookIdDelete
     */
    readonly id: number
}

/**
 * Request parameters for apiBooksGetBookByIdIdGet operation in BooksApi.
 * @export
 * @interface BooksApiApiBooksGetBookByIdIdGetRequest
 */
export interface BooksApiApiBooksGetBookByIdIdGetRequest {
    /**
     * 
     * @type {number}
     * @memberof BooksApiApiBooksGetBookByIdIdGet
     */
    readonly id: number
}

/**
 * Request parameters for apiBooksPostBookPost operation in BooksApi.
 * @export
 * @interface BooksApiApiBooksPostBookPostRequest
 */
export interface BooksApiApiBooksPostBookPostRequest {
    /**
     * 
     * @type {BookDto}
     * @memberof BooksApiApiBooksPostBookPost
     */
    readonly bookDto?: BookDto
}

/**
 * Request parameters for apiBooksPutBookIdPut operation in BooksApi.
 * @export
 * @interface BooksApiApiBooksPutBookIdPutRequest
 */
export interface BooksApiApiBooksPutBookIdPutRequest {
    /**
     * 
     * @type {number}
     * @memberof BooksApiApiBooksPutBookIdPut
     */
    readonly id: number

    /**
     * 
     * @type {BookDto}
     * @memberof BooksApiApiBooksPutBookIdPut
     */
    readonly bookDto?: BookDto
}

/**
 * BooksApi - object-oriented interface
 * @export
 * @class BooksApi
 * @extends {BaseAPI}
 */
export class BooksApi extends BaseAPI {
    /**
     * 
     * @param {BooksApiApiBooksDeleteBookIdDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public apiBooksDeleteBookIdDelete(requestParameters: BooksApiApiBooksDeleteBookIdDeleteRequest, options?: AxiosRequestConfig) {
        return BooksApiFp(this.configuration).apiBooksDeleteBookIdDelete(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BooksApiApiBooksGetBookByIdIdGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public apiBooksGetBookByIdIdGet(requestParameters: BooksApiApiBooksGetBookByIdIdGetRequest, options?: AxiosRequestConfig) {
        return BooksApiFp(this.configuration).apiBooksGetBookByIdIdGet(requestParameters.id, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public apiBooksGetBooksGet(options?: AxiosRequestConfig) {
        return BooksApiFp(this.configuration).apiBooksGetBooksGet(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BooksApiApiBooksPostBookPostRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public apiBooksPostBookPost(requestParameters: BooksApiApiBooksPostBookPostRequest = {}, options?: AxiosRequestConfig) {
        return BooksApiFp(this.configuration).apiBooksPostBookPost(requestParameters.bookDto, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {BooksApiApiBooksPutBookIdPutRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof BooksApi
     */
    public apiBooksPutBookIdPut(requestParameters: BooksApiApiBooksPutBookIdPutRequest, options?: AxiosRequestConfig) {
        return BooksApiFp(this.configuration).apiBooksPutBookIdPut(requestParameters.id, requestParameters.bookDto, options).then((request) => request(this.axios, this.basePath));
    }
}

